### PR TITLE
Add error classes for additional error codes

### PR DESCRIPTION
**Pull request by adamyala**
Added error classes per RFC 6585
- Error Code 428 Precondition Required
- Error Code 429 Too Many Requests
- Error Code 431 Request Header Fields Too Large
- Error Code 511 Network Authentication Required

https://github.com/falconry/falcon/issues/561

### CODE REVIEW

**Comment by adamyala** [comment]
Found a bunch of things I forgot to add. Will update, rebase, and remake pull request.

**Comment by kgriffs** [comment]
Hi @adamyala, just following up on this. "429 Too Many Requests" has been implemented by another contributor, but we are still missing the others. Thanks!

**Comment by kgriffs** [comment]
P.S. - You may wish to open a new PR to score some some https://hacktoberfest.digitalocean.com points. 😄

**Comment by wssbck** [comment]
@adamyala Are you going to continue working on this PR? I had a similar idea as well - making sure all errors have their classes and tests.

**Comment by wssbck** [comment]
@kgriffs I could take over this PR or open a new one that does the same thing, as a follow up to #834

**Comment by adamyala** [comment]
@wssbck all yours. I unfortunately having had the time to revisit this one.

**Comment by kgriffs** [comment]
Hi @wssbck, did you still want to take this and get it over the finish line? It would be good to get it done in the next couple of weeks if you have the bandwidth. Just let me know. Thanks!

**Comment by wssbck** [comment]
@kgriffs I should be able to finish it over the next two weeks.

**Comment by wssbck** [comment]
@kgriffs @adamyala as #973 is merged, this PR can be closed I think.

**Pull request closed without merging**
