### PR TITLE
chore(adds print-api-routes): new utility to print routes

### PR DESCRIPTION
**Pull request by ashcrow**
While doing some documentation work I realized it would be nice to have a quick script that dumps out route information and wrote this. I think it may be helpful for other folks as well.

### CODE REVIEW

**Comment by kgriffs** [comment]
@ashcrow Good idea! What do you think about moving this under falcon/cmd and adding it as a `'console_script'` entry point? Up to this point, the tools directory has only been used for things related to building and packaging of the framework.

Regardless, it would be great to have some tests for this as well. Thanks!

**Comment by ashcrow** [comment]
@kgriffs Sounds good to me. Being part of the codebase proper I agree tests make sense and will add some :smile:

**Comment by yohanboniface** [comment]
I'd say it's a good candidate for a plugin.

**Comment by ashcrow** [comment]
:arrow_up: Moved to a command and added a few tests.

**Comment by jmvrbanac** [comment]
:+1: LGTM

**Comment by kgriffs** [comment]
Nice work, thanks!

**Pull request merged**
