### PR TITLE
docs(middleware): fix typo in middleware

### PR DESCRIPTION
**Pull request by CaselIT**
Just a short documentation typo fix.

I've just noticed that github from the website does not place the branch on my fork. Sorry about that

### CODE REVIEW

**Comment by CaselIT** [comment]
I'm not sure if I can delete the branch on this repo that I mistakenly opened when doing this change

**Comment by vytas7** [comment]
I think you can.

**Comment by CaselIT** [comment]
I'll try later from the pc. I cannot find a way from the phone

**Comment by vytas7** [comment]
Sure; it is by no means urgent.

**Comment by CaselIT** [comment]
not sure why, but is seems to be marked by github as protected, so I cannot delete it

**Comment by vytas7** [comment]
I had to temporarily lift the respective protection rule to achieve this. Done now.

**Pull request merged**
