### PR TITLE
Additional error classes

### PR DESCRIPTION
**Pull request by wssbck**
This PR is an effort to complete #576

Classes to add:

- [x] 428 Precondition Required
- [x] 431 Request Header Fields Too Large
- [x] 511 Network Authentication Required

### CODE REVIEW

**Comment by wssbck** [comment]
@kgriffs @adamyala This is where I will continue #576

**Comment by kgriffs** [comment]
Looks like this needs a test to ensure 100% coverage?

**Comment by wssbck** [comment]
@kgriffs It is not complete yet, I will add tests as well. Sorry, life circumstances, will finish this week, weekend latest.

**Comment by wssbck** [comment]
@kgriffs Done. I noticed there were still some error statuses with no classes (402, 407, etc) but for those I will open another one.

**Pull request merged**
