### PR TITLE
docs(examples/asgilook): update aioredis version to 2.0

### LINKED ISSUE #1938: Update asgi look examples to use aioredis 2
A new major vesion of aioredis was released, and it has some api changes.
This is the changelog https://github.com/aio-libs/aioredis-py/blob/master/CHANGELOG.md

### PR DESCRIPTION
**Pull request by the-bets**
# Summary of Changes

Update `aioredis` to version 2.0, the impact of which is found in the `asgilook` examples. Apply necessary code and API changes as well as update asgilook tutorial.

Both `tools/mintest.sh` and `tox --recreate -e asgilook` pass with these updates. Docs (for the tutorial) were also successfully built and changes correctly shown.

# Related Issues

fixes #1938 

# Pull Request Checklist

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [x] Applied changes to both WSGI and ASGI code paths and interfaces (where applicable).
- [x] Added **tests** for changed code.
- [x] Prefixed code comments with GitHub nick and an appropriate prefix.
- [x] Coding style is consistent with the rest of the framework.
- [x] Updated **documentation** for changed code.
    - [x] Added docstrings for any new classes, functions, or modules.
    - [x] Updated docstrings for any modifications to existing code.
    - [x] Updated both WSGI and ASGI docs (where applicable).
    - [x] Added references to new classes, functions, or modules to the relevant RST file under `docs/`.
    - [x] Updated all relevant supporting documentation files under `docs/`.
    - [x] A copyright notice is included at the top of any new modules (using your own name or the name of your organization).
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/usage/restructuredtext/directives.html?highlight=versionadded#directive-versionadded).
- [x] Changes (and possible deprecations) have [towncrier](https://towncrier.readthedocs.io/en/actual-freaking-docs/index.html) news fragments under `docs/_newsfragments/`, with the file name format `{issue_number}.{fragment_type}.rst`. (Run `towncrier --draft` to ensure it renders correctly.)

If you have *any* questions to *any* of the points above, just **submit and ask**! This checklist is here to *help* you, not to deter you from contributing!

*PR template inspired by the attrs project.*

### CODE REVIEW

**Review by vytas7 — COMMENTED** [review]
This looks really good, thanks!

If possible, I would like to keep an example demonstrating the use of ASGI `process_startup`, IIRC we were even linking to that example from FAQ (or were going to).
I understand that `aioredis` has changed design so that pool initialization is now a synchronous function. But could we maybe _invent_ a use case for async `process_startup` (or alternatively `process_shutdown`)?

(See also https://github.com/falconry/falcon/discussions/1981 & https://github.com/falconry/falcon/pull/1982)

**Comment by CaselIT** [comment]
> But could we maybe _invent_ a use case for async `process_startup` (or alternatively `process_shutdown`)?

Maybe we could ping the server in `process_startup` using `await self._redis.ping()` and close the pool in `process_shutdown` by doing `await self._redis.connection_pool.disconnect()`?

**Comment by vytas7** [comment]
Yeah that sounds great @CaselIT ! That makes sense because as I understand `aioredis.from_url(...)` just instantiates an object, you can provide any URL there, even if the referenced server is down or broken.

I think `process_startup` is enough though :sweat_smile:

**Comment by the-bets** [comment]
Sounds good! Thanks for the review, we'll plan on adding in that `process_startup`/`process_shutdown` example this week.

**Comment by vytas7** [comment]
Hi again @the-bets , just checking if you are going to have an opportunity to work on that `process_startup` example?
Otherwise I'm thinking we could add this ourselves in a followup PR, as your changeset seems to be really well polished as-is, and maybe we don't need to delay merging just because of the lack of that example.

**Comment by the-bets** [comment]
> Hi again @the-bets , just checking if you are going to have an opportunity to work on that `process_startup` example?
> 
> Otherwise I'm thinking we could add this ourselves in a followup PR, as your changeset seems to be really well polished as-is, and maybe we don't need to delay merging just because of the lack of that example.

Hello again! Thanks for checking in. Mihai and I both got busy with work and life since the last time we talked on this PR. Neither of us have gotten to writing that example yet, and with this being a travel/holiday week for 1/2 of us, we probably won't get to it soon. We do not mind this PR being merged as-is for the time being.

If you want to add the example yourselves, that's also fine with us! We are still down to add it, but again likely won't get to it this week.

**Comment by vytas7** [comment]
Thanks for the update!
It's not _that_ urgent, so if you're still committed to it, we can keep this open until we are approaching a release.

**Review by vytas7 — APPROVED** [review]
This LGTM now :100: 
(I took the liberty of fixing a couple of trivial/cosmetic issues to get the CI to pass.)

**Review by CaselIT — APPROVED** [review]
Thanks!

**Comment by the-bets** [comment]
Thank you @vytas7 and @CaselIT for the input, patience, and quick merge!

**Pull request merged**
