### PR TITLE
docs(tutorial): fix typos and failing test in the tutorial

### PR DESCRIPTION
**Pull request by cravindra**
docs(tutorial): fix typos and test in the tutorial

# Summary of Changes
There was a failing test because of breaking changes in `2.0.0` - check for an instance of `wsgiref.validate.InputWrapper` instead of `falcon.request_helpers.BoundedStream`.  Minor typo fix in the tutorial.

# Related Issues
[Test described in tutorial fails #1554](https://github.com/falconry/falcon/issues/1554)

# Pull Request Checklist

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](https://github.com/falconry/falcon/blob/master/CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [x] Added **tests** for changed code.
- [x] Prefixed code comments with GitHub nick and an appropriate prefix.
- [x] Coding style is consistent with the rest of the framework.
- [x] Updated **documentation** for changed code.
    - [x] Added docstrings for any new classes, functions, or modules.
    - [x] Updated docstrings for any modifications to existing code.
    - [x] Added references to new classes, functions, or modules to the relevant RST file under `docs/`.
    - [x] Updated all relevant supporting documentation files under `docs/`.
    - [x] A copyright notice is included at the top of any new modules (using your own name or the name of your organization).
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/usage/restructuredtext/directives.html?highlight=versionadded#directive-versionadded).
- [x] Changes (and possible deprecations) have [towncrier](https://pypi.org/project/towncrier/) news fragments under `docs/_newsfragments/`. (Run `towncrier --draft` to ensure it renders correctly.)

### CODE REVIEW

**Comment by cravindra** [comment]
Hello!

I'm not sure why the docs build is failing... Can anyone help me understand what I'm doing wrong?

**Comment by xakiy** [comment]
Didn't you missed to check the failing build log at here https://travis-ci.org/falconry/falcon/jobs/552259189

It says:

> Warning, treated as error:

>duplicate object description of falcon, other instance in api/errors, use :noindex: for one of them

>ERROR: InvocationError for command /home/travis/build/falconry/falcon/.tox/docs/bin/sphinx-build -j 4 -W -E -b html docs docs/_build/html (exited with code 2)

**Comment by vytas7** [comment]
Hi @cravindra !
And thanks for this contribution!

Any specific reasons why you have closed this PR? I have reopened it if you don't mind.

Re the failing docs, it is clearly coming from the master branch, and isn't your fault. I'll take a look at it.

**Comment by cravindra** [comment]
Hello @vytas7!

Thank you! I was not sure how to make the tests pass. I'm super new to Python/Falcon in general so I assumed it must be something I did wrong and closed the PR because I wasn't sure when I'd get around to figuring it out.

**Comment by vytas7** [comment]
Hi again @cravindra !
and sorry we took so long to get back to you.

This is looking mostly great, however, could it be possible to actually run these test in the (Travis) CI to make sure we do not introduce a regression again?

**Comment by cravindra** [comment]
@vytas7 I'd be happy to help! But I'm not sure what exactly needs to be done. Should I open a new PR with all the latest changes so that the Travis checks kick in or is there another way to do it?

**Comment by kgriffs** [comment]
Thanks! This code looks good to me.

As @vytas7 suggested, it would be good to add tests for this code in the tutorial to make sure it doesn't break again in the future as the project evolves. We should probably be doing this as a general rule going forward.

**Comment by vytas7** [comment]
@cravindra sorry if I was unclear. Travis kicks in upon every commit, including merging `master` to branch that we've done here many times.
The issue that we have no definitions in Tox or Travis that would run invoke the test that you fixed.

But I'm thinking to nevertheless go on to merge this PR. Great effort @cravindra :tada: :+1: 
I'll look into automating these tests in a follow-up PR.

**Pull request merged**
