### PR TITLE
fix(Request): Properly handle quoted strings in forwarded header

### PR DESCRIPTION
**Pull request by Just-Sieb**
I have implemented a fix for issue #1116. 

In the case of the malformed forwarded header I decided to just say the whole forwarded is malformed and set it to None.

### CODE REVIEW

**Comment by vfaronov** [comment]
The [quoted-string](https://tools.ietf.org/html/rfc7230#section-3.2.6) syntax used by RFC 7239 permits escaped quotes:

    Forwarded: for=1.2.3.4;some="other \"info"

Your implementation does not deal with these correctly.

> In the case of the malformed forwarded header I decided to just say the whole forwarded is malformed and set it to None.

May I suggest reflecting this in the [docs](http://falcon.readthedocs.io/en/stable/api/request_and_response.html#Request.forwarded).

**Comment by kgriffs** [comment]
> In the case of the malformed forwarded header I decided to just say the whole forwarded is malformed and set it to None.

That's probably OK, although we should advise that the app should be suspicious of malicious intent in this case and if it decides to respond to the request, it should use safe defaults for any information it uses in the header. 

> Your implementation does not deal with these correctly.

At first glance, I'm not certain that aiohttp deals with escaped quotes either (but I could be wrong). I think we need to handle this in any case. See also https://tools.ietf.org/html/rfc7230#section-3.2.6 

    The backslash octet ("\") can be used as a single-octet quoting
    mechanism within quoted-string and comment constructs.  Recipients
    that process the value of a quoted-string MUST handle a quoted-pair
    as if it were replaced by the octet following the backslash.

     quoted-pair    = "\" ( HTAB / SP / VCHAR / obs-text )

Finally, I'd like to explore the performance of the different approaches (current, this patch, aiohttp's).  If it is faster to do the comma-splitting as currently implemented, we can simply check for the presence of any double-quote's in the string and only use the slower algorithm if any are present.

Thoughts?

**Comment by vfaronov** [comment]
> At first glance, I'm not certain that aiohttp deals with escaped quotes either (but I could be wrong).

It does: see, for example, [`test_single_forwarded_header_custom_param`](https://github.com/aio-libs/aiohttp/blob/dbb8d9a63f6ffba0ae7e4592158045e54c26433a/tests/test_web_request.py#L277).

> we can simply check for the presence of any double-quote's in the string and only use the slower algorithm if any are present

Sure, that’s an option.

**Comment by kgriffs** [comment]
Ah, yes, I misread the regex. It does indeed include VCHARS in the character set.

@Just-Sieb Do you have some bandwidth to get this PR over the finish line this week?

- [ ] Resolve `quoted-pair`'s per [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2.6). Add tests to cover this case.
- [ ] Benchmark the relative performance of the current implementation vs. the one in this PR vs. the one used by aiohttp. This could be as simple as pasting some test functions into IPython and using `%timeit`. Be sure to check Python 2.7, Python 3.5 and 3.6 (via, e.g., pyenv).
- [ ] Based on the benchmark results above, optimize this PR's implementation. Use alternative strategies if necessary, based on whether the header value contains any double quotes.

**Comment by kgriffs** [comment]
@Just-Sieb No worries if you don't have the time. If you don't mind, I may just go ahead and finish up the work on this so we can get 1.4 out the door.

**Comment by kgriffs** [comment]
OK, I went ahead and used the aiohttp algorithm with a few modifications. It is faster than Just-Sieb's original solution, and more robust in dealing with malformed values and quoted-pair's. However, the regex solution isn't quite as fast as the current implementation in master, but it is close enough (within a few microseconds) that I didn't think it would be worth maintaining two code paths.

**Comment by kgriffs** [comment]
Hmm, it seems codecov is on the fritz again?

**Comment by kgriffs** [comment]
@jmvrbanac If this looks good to you, feel free to merge without waiting on codecov.

**Pull request merged**
