### PR TITLE
fix(request): prevent IndexError from broken Forwarded header

### PR DESCRIPTION
**Pull request by TBoshoven**
# Summary of Changes

Fix a wrongful assumption where `forwarded_scheme` and `forwarded_host` assume that if a `Forwarded` header is present, it is valid.
When a `Forwarded` header cannot be parsed properly (or is plain empty), an empty list is returned by `forwarded`.
This resulted in an `IndexError` in `forwarded_scheme` and `forwarded_host`.
This PR changes that to use the existing fallback logic instead.

While we could fall back on checking other headers (`X-Forwarded-For` and such) I think that if the `Forwarded` header is present but doesn't contain any relevant or correct entries, we can simply assume that there are none.
Please let me know if you have a different opinion.

# Related Issues

N/A

# Pull Request Checklist

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [X] Applied changes to both WSGI and ASGI code paths and interfaces (where applicable).
- [X] Added **tests** for changed code.
- [X] Prefixed code comments with GitHub nick and an appropriate prefix.
- [X] Coding style is consistent with the rest of the framework.
- [X] Updated **documentation** for changed code.
    - [X] Added docstrings for any new classes, functions, or modules.
    - [X] Updated docstrings for any modifications to existing code.
    - [X] Updated both WSGI and ASGI docs (where applicable).
    - [X] Added references to new classes, functions, or modules to the relevant RST file under `docs/`.
    - [X] Updated all relevant supporting documentation files under `docs/`.
    - [X] A copyright notice is included at the top of any new modules (using your own name or the name of your organization).
    - [X] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/usage/restructuredtext/directives.html?highlight=versionadded#directive-versionadded).
- [x] Changes (and possible deprecations) have [towncrier](https://towncrier.readthedocs.io/en/actual-freaking-docs/index.html) news fragments under `docs/_newsfragments/`, with the file name format `{issue_number}.{fragment_type}.rst`. (Run `towncrier --draft` to ensure it renders correctly.)

### CODE REVIEW

**Review by vytas7 — CHANGES_REQUESTED** [review]
Hi @TBoshoven,
and sorry for a slight delay on this as we are in the process of getting Falcon 3.1.0 out (and not because I work for a competitor of yours :smiling_imp:). This PR won't make it to the impending release as we have already published a release candidate.

You code looks good :+1:

Before merging though, you'll need to merge the updated `master` into your branch as you didn't grant maintainer access. In addition, the proposed newsfragment needs some polishing, ideally linking to the referenced properties and classes, and/or using double backticks where applicable.

We'll circle back on this as soon as 3.1.0 is released.

**Review by vytas7 — APPROVED** [review]
This looks good, thanks!

Before merging, you'll need to merge master into your branch though, or grant us maintainer access to your PR.

**Review by CaselIT — APPROVED** [review]

**Review by kgriffs — APPROVED** [review]

**Comment by TBoshoven** [comment]
Sorry for taking a while. Merged `master` into this branch.

**Comment by kgriffs** [comment]
Thanks @TBoshoven !

**Pull request merged**
