### PR TITLE
fix: implement `close()` method for asgi static files

### LINKED ISSUE #1963: StaticRouteAsync leaves open files
When using static routes with a [`falcon.asgi.App`](https://falcon.readthedocs.io/en/stable/api/app.html#asgi-app), it seems that the `_AsyncFileReader` wrapper does not implement any `.close()` method, so files are left open.

On CPython, I wasn't able to demonstrate any practical impact of this bug as the file object in question is refcounted to 0 and garbage collected as soon as it goes out of scope. However, that isn't the case when running `uvicorn` on PyPy 3.7, as PyPy uses a different GC implementation.

Test case in point:
```
import io
import logging
import os.path
import unittest.mock

import falcon.asgi

logging.basicConfig(
    format='%(asctime)s [%(levelname)s] %(message)s', level=logging.INFO)


class DebugIO(io.BytesIO):

    @classmethod
    def open(cls, *args, **kwargs):
        return cls(b'Test data!\n')

    def close(self):
        logging.info(f'{self}.close()')
        super().close()


app = falcon.asgi.App()
app.add_static_route('/files', '/tmp')

debug = unittest.mock.patch('io.open', DebugIO.open)
debug.start()
```

### PR DESCRIPTION
**Pull request by Contessina**
# Summary of Changes

Implement `close()` method for `_AsyncFileReader`

# Related Issues

Fixes #1963 

# Pull Request Checklist

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [x] Applied changes to both WSGI and ASGI code paths and interfaces (where applicable).
- [x] Added **tests** for changed code.
- [x] Prefixed code comments with GitHub nick and an appropriate prefix.
- [x] Coding style is consistent with the rest of the framework.
- [x] Updated **documentation** for changed code.
    - [x] Added docstrings for any new classes, functions, or modules.
    - [x] Updated docstrings for any modifications to existing code.
    - [x] Updated both WSGI and ASGI docs (where applicable).
    - [x] Added references to new classes, functions, or modules to the relevant RST file under `docs/`.
    - [x] Updated all relevant supporting documentation files under `docs/`.
    - [x] A copyright notice is included at the top of any new modules (using your own name or the name of your organization).
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/usage/restructuredtext/directives.html?highlight=versionadded#directive-versionadded).
- [x] Changes (and possible deprecations) have [towncrier](https://towncrier.readthedocs.io/en/actual-freaking-docs/index.html) news fragments under `docs/_newsfragments/`, with the file name format `{issue_number}.{fragment_type}.rst`. (Run `towncrier --draft` to ensure it renders correctly.)

If you have *any* questions to *any* of the points above, just **submit and ask**! This checklist is here to *help* you, not to deter you from contributing!

*PR template inspired by the attrs project.*

### CODE REVIEW

**Review by vytas7 — CHANGES_REQUESTED** [review]
Thanks for this contribution!

Your code looks good, however (as you correctly marked in the check list), we need to add some tests to make sure the new method is called when expected (according to coverage, it is at least once _somewhere_, but we need to make sure it is called when we expect it).

**Comment by vytas7** [comment]
Hi again @Contessina!
Just checking if you are planning to work on adding tests for the bug that you fixed?
(You could probably adapt my snippet from the issue's description to get started: https://github.com/falconry/falcon/issues/1963#issue-1021755137.)

**Comment by Contessina** [comment]
> Hi again @Contessina! Just checking if you are planning to work on adding tests for the bug that you fixed? (You could probably adapt my snippet from the issue's description to get started: [#1963 (comment)](https://github.com/falconry/falcon/issues/1963#issue-1021755137).)

Hi there.
I included the suggestions for the news fragment and also implemented test for this scenario.

As expected, the test fails before my code changes and passes afterwards (tested on python3.8 and pypy3). The test uses a custom exception somewhat counter-intuitively, but I could not find a better way to test the side effect. I am open to suggestions if you think of a better way to implement this.

**Comment by vytas7** [comment]
Just using a custom exception that way is fine _per se_ for implementing tests, however it's potentially an issue if we ever decide to address https://github.com/falconry/falcon/issues/1865.

You could instead just monkeypatch that method to a custom function, that would register the call in a local variable/closure, or use `unittest.mock`, and inspect if the patched object was called.

Moreover, we have recently refactored these tests somewhat, so you may need to check the latest changes coming from the master branch.

**Comment by wsz** [comment]
Hi! I was researching how to approach the issue, just before @Contessina created the PR.
I would recommend moving `stream.read()` and `stream.close()` inside a `try: ... finally: ...` block [here in asgi/app.py](https://github.com/falconry/falcon/blob/master/falcon/asgi/app.py#L703). This way, we can ensure the stream is always closed at the end, even if `read()` or any other call raises an exception.

**Comment by vytas7** [comment]
Hi @wsz!
Spot on regarding restructuring how `.close()` ought to be ensured in a `finally` block.

In fact, there is a separate issue (https://github.com/falconry/falcon/issues/1943) with a lingering PR, maybe you would like to take over that one?

**Comment by vytas7** [comment]
Hi again @Contessina  -- I took the liberty of tweaking the proposed news fragment somewhat, check if I haven't distorted it too much.

I'll finish reviewing the test later today; it was behaving a bit strange when I was digging a bit more in depth, but that could have well been my fault.

**Review by vytas7 — APPROVED** [review]
LGTM now! (I've just made a couple of minor tweaks.)

**Review by CaselIT — APPROVED** [review]

**Pull request merged**
