### PR TITLE
doc(Tutorial): Fixed hooks interface in tutorial

### PR DESCRIPTION
**Pull request by muodov**
Hooks section in the Tutorial was a bit misleading because hooks interface in examples was outdated.

### CODE REVIEW

**Comment by jmvrbanac** [comment]
:+1:

**Comment by jmvrbanac** [comment]
Looks good, but could you change the commit message to follow the project conventions: https://github.com/falconry/falcon/blob/master/CONTRIBUTING.md#commit-message-format

In this case, I believe it would be: "doc(Tutorial):"

**Comment by muodov** [comment]
Sure :)

**Comment by jmvrbanac** [comment]
Awesome thanks! :+1:

**Pull request merged**
