### PR TITLE
chore: add VS Code dev container

### LINKED ISSUE #1979: Would you consider maintaining a devcontainer for VS Code?
I struggled a bit to get `tools/mintest.sh` to run and since I'm not a very experienced Python developer, setting up the prerequisites on OSX proved to be a challenge. Having multiple versions of Python in parallel seems a bit error-prone to me. I guess using `pyenv` from the start is the way to go, but wasn't sure based on the instructions from [here](https://github.com/falconry/falcon/blob/master/CONTRIBUTING.md). On the other hand, I recently played around with a project called Keda and I found [their devcontainer setup](https://github.com/kedacore/keda/tree/main/.devcontainer) quite easy to use, assuming one is willing to run Docker. Basically, VS Code starts a headless server in the container automatically and then the UI communicates with it seamlessly.

For Falcon, I found it easier to install all the dependencies in a Docker container and run everything there without worrying about messing up Python on my local laptop:
```shell
> docker run --rm -it -v$(pwd):/workspace ubuntu bash
>> apt update && DEBIAN_FRONTEND=noninteractive apt install -y software-properties-common ca-certificates curl build-essential python3-distutils python3-pip
>> add-apt-repository -y ppa:deadsnakes/ppa && apt update
>> apt install -y python3.5 python3.8 python3.5-dev python3.8-dev
>> pip install -U pip setuptools tox wheel
>> cd /workspace
>> # Run mintest
>> tools/mintest.sh
>> # Run asgilook test
>> tox --recreate -e asgilook
>> # Run asgilook tests without refreshing dependencies
>> tox --skip-pkg-install -e asgilook
```

I can easily wrap the above in a devcontainer if you'd like.

### PR DESCRIPTION
**Pull request by mihaitodor**
# Summary of Changes

This adds the required config for VS Code [Dev Container](https://code.visualstudio.com/docs/devcontainers/containers) support. With this change, opening the repo in VS Code will prompt you to reload the editor and, assuming you have Docker up and running, it will pull the required Docker image and start it. Expect it to download a 1.4GB image. Once the container is running, it will install a bunch of dependencies, including `tox`. It will show you the log as it progresses, but, at the end of the process, VS Code will run in this container in headless mode and you can open a separate terminal in which you can run the `tox` command which should complete successfully.

I haven't spotted any specific section related to the code editor in the Readme / Contributing docs, so not sure if you'd like to have a paragraph about this feature, or at least mention somewhere that people will want to use VS Code if they wish to leverage this Dev Container setup for their work / tests.

# Related Issues

Fixes #1979.

# Pull Request Checklist

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [ ] Applied changes to both WSGI and ASGI code paths and interfaces (where applicable).
- [ ] Added **tests** for changed code.
- [ ] Prefixed code comments with GitHub nick and an appropriate prefix.
- [ ] Coding style is consistent with the rest of the framework.
- [ ] Updated **documentation** for changed code.
    - [ ] Added docstrings for any new classes, functions, or modules.
    - [ ] Updated docstrings for any modifications to existing code.
    - [ ] Updated both WSGI and ASGI docs (where applicable).
    - [ ] Added references to new classes, functions, or modules to the relevant RST file under `docs/`.
    - [ ] Updated all relevant supporting documentation files under `docs/`.
    - [ ] A copyright notice is included at the top of any new modules (using your own name or the name of your organization).
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/usage/restructuredtext/directives.html?highlight=versionadded#directive-versionadded).
- [ ] Changes (and possible deprecations) have [towncrier](https://towncrier.readthedocs.io/en/latest/quickstart.html#creating-news-fragments) news fragments under `docs/_newsfragments/`, with the file name format `{issue_number}.{fragment_type}.rst`. (Run `towncrier --draft` to ensure it renders correctly.)

If you have *any* questions to *any* of the points above, just **submit and ask**! This checklist is here to *help* you, not to deter you from contributing!

*PR template inspired by the attrs project.*

### CODE REVIEW

**Comment by CaselIT** [comment]
I've tried using podman on wsl fedora and everything seems to work but I've had to uncomment `"remoteUser": "root"` or is was failing to copy some stuff when initializing the container.

This is probably a potman thing only since I think it will not run containers as root contrary to docker.

I think we could keep as is. @vytas7 thoughts?

**Review by CaselIT — COMMENTED** [review]
As suggested in the issue a couple of lines could be added in the contributing file

looking ok otherwise

**Comment by mihaitodor** [comment]
@CaselIT Thanks for testing! I added some documentation as requested. If you think it's too detailed / wordy, I'm happy to adjust it.

**Review by CaselIT — APPROVED** [review]

**Comment by vytas7** [comment]
(It seems that `flake8-import-order` has now been updated with support for the newest `flake8`, rerunning the CI.)

**Review by vytas7 — APPROVED** [review]
As I understand, this needs to be enabled manually by the developer, so it shouldn't cause any problems for other VS Code users. So if it can potentially lower the barrier to contribution, why not? :tada:

**Comment by mihaitodor** [comment]
Yeah, they'll be asked when they open the project in VS Code if they want to reopen it in a Dev Container, but they can just click no.

**Comment by vytas7** [comment]
Aha, OK, I didn't know that VSCode would ask that question automatically. But let's give it a try, we can always disable this if we get more negative than positive feedback.

**Comment by CaselIT** [comment]
It's just a notification, you can just ignore it too, so it should be fine

**Comment by vytas7** [comment]
I see; I've just tested it myself for the heck of it, and it should be fine :100: Let's see if anyone complains :smiling_imp:

**Pull request merged**
