### PR TITLE
feat(media): simplify JSON media handlers

### LINKED ISSUE #1717: Custom media handlers: Unexpected issue when providing custom json handler
This is in falcon-2.0

Look at the documentation [here][1] for using rapidjson for encoding/decoding json. By providing:

`extra_handlers={'application/json': json_handler}` we are still left with the default handler for content-type `application-json; charset=UTF-8`. This results in an unexpected behaviour when some client library (e.g. Retrofit for Android) includes the charset in the header. 

While the documentation should be updated, the expected behaviour is that if the handler for `application/json` is updated - it should also update the handler for variant with charset (or at least throw a warning) otherwise there is a possibility of hidden bugs. 

[1]: https://falcon.readthedocs.io/en/stable/api/media.html

### PR DESCRIPTION
**Pull request by adsahay**
# Summary of Changes

Solves unexpected behaviour due to a separate handler specified for `application/json; charset=utf8` which used the default json handler. 

# Related Issues

Closes #1717 

# Pull Request Checklist

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [ ] Applied changes to both WSGI and ASGI code paths and interfaces (where applicable).
- [ ] Added **tests** for changed code.
- [ ] Prefixed code comments with GitHub nick and an appropriate prefix.
- [ ] Coding style is consistent with the rest of the framework.
- [ ] Updated **documentation** for changed code.
    - [ ] Added docstrings for any new classes, functions, or modules.
    - [ ] Updated docstrings for any modifications to existing code.
    - [ ] Updated both WSGI and ASGI docs (where applicable).
    - [ ] Added references to new classes, functions, or modules to the relevant RST file under `docs/`.
    - [ ] Updated all relevant supporting documentation files under `docs/`.
    - [ ] A copyright notice is included at the top of any new modules (using your own name or the name of your organization).
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/usage/restructuredtext/directives.html?highlight=versionadded#directive-versionadded).
- [ ] Changes (and possible deprecations) have [towncrier](https://towncrier.readthedocs.io/en/actual-freaking-docs/index.html) news fragments under `docs/_newsfragments/`, with the file name format `{issue_number}.{fragment_type}.rst`. (Run `towncrier --draft` to ensure it renders correctly.)

If you have *any* questions to *any* of the points above, just **submit and ask**! This checklist is here to *help* you, not to deter you from contributing!

*PR template inspired by the attrs project.*

### CODE REVIEW

**Comment by adsahay** [comment]
@vytas7 Please review this. I could no longer find the responsible documentation (which was present in 2.0) to add a remark about the effect of this change. I've tested different scenarios but I didn't find any tests to update - the usual media handler tests are all passing. 

As this is my first time contributing code please let me know if I'm missing something.

**Review by CaselIT — APPROVED** [review]
Looks good. Thanks!

**Review by vytas7 — CHANGES_REQUESTED** [review]
This is looking good indeed, thanks!

However, I would like to see a couple of improvements before merging this. Following up your own comments actually :slightly_smiling_face: 
> I could no longer find the responsible documentation (which was present in 2.0) to add a remark about the effect of this change.

We are now using [Towncrier](https://github.com/twisted/towncrier) to manage changelogs. In this particular casee, IMHO we should add `docs/_newsfragments/1717.newandimproved.rst`.

> I've tested different scenarios but I didn't find any tests to update - the usual media handler tests are all passing.

Right now we are only relying on `TestFalconTestingUtils::test_simulate_json_body` to validate the effect of your change, which is a test that I wrote for some other purpose.
While this does the basic job, maybe we could add a new test reflecting your story reported in the issue? Parametrized in a way that
* `application/json`, `application/json; charset=UTF-8` are accepted by the default handlers, whereas some other types, e.g., `application/yaml` etc are not.
* same test after updating with `extra_handlers`, however, also verify that JSON media was handled by the newly installed handler.

**Comment by adsahay** [comment]
@vytas7 What is a good way (in the tests) to assert which media handler was called?

**Comment by vytas7** [comment]
@adsahay whatever you like :slightly_smiling_face: 
In the absence of better ideas, you could, for instance, increase some attribute (for each `content_type` deserialized) on the handler itself, to later `assert` it is in line with your expectation.

**Comment by adsahay** [comment]
Need some help with a failing test:

```=========================== short test summary info ============================
FAILED tests/test_utils.py::TestFalconTestingUtils::test_simulate_content_type[application/json]
FAILED tests/test_utils.py::TestFalconTestingUtils::test_simulate_content_type[application/json; charset=UTF-8]
========== 2 failed, 1730 passed, 864 skipped, 13 warnings in 16.12s ===========
ERROR: InvocationError for command /home/runner/work/falcon/falcon/.tox/py35/bin/coverage run -m pytest tests --ignore=tests/asgi (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py35: commands failed
Error: Process completed with exit code 1.```

Is it ok to use mocks to identify if a function is called?

**Comment by vytas7** [comment]
@adsahay it seems that `unittest.mock` shipped with CPython 3.5.2 stdlib is not good enough for our use.

We should refactor that test, either by not relying on mocking at all (or restricting our use to `unittest.mock` 3.5 functionality) or by using another mocking utility such as [`pytest`'s `monkeypatch` fixture](https://docs.pytest.org/en/stable/monkeypatch.html).

**Comment by vytas7** [comment]
@adsahay I have taken the liberty of slightly adjusting your tests and the newsfragment.
Please check if I haven't vandalized them too much wrt your original intent.

**Review by vytas7 — APPROVED** [review]
Thanks for working on this!

**Review by CaselIT — APPROVED** [review]

**Comment by adsahay** [comment]
Looking good! Sorry about the amateur bits.

**Pull request merged**
