### PR TITLE
chore(tox): lower the barrier to contribution

### LINKED ISSUE #1983: Simplify and clarify CONTRIBUTING.md
As discussed in #1979, the current [CONTRIBUTING.md](CONTRIBUTING.md) document instructs people to run `tools/mintest.sh`, which requires Python 3.8 and 3.5 installed simultaneously and then it makes things a bit confusing when referencing Python 3.6 or 3.7 and then `pyenv shell 3.8.0 3.5.8` and then further below `pyenv virtualenv 3.8.0 falcon-sandbox-38`. I'm not familiar with `pyenv`, but this is quite confusing and I assume also hard to maintain when new Python versions are released.

As @CaselIT [mentioned](https://github.com/falconry/falcon/issues/1979#issuecomment-953118480) in #1979, perhaps it's best to ask people to run only `tox -e pep8 py` before creating a PR and let the CI run additional checks.

I think power users might expect to have a standalone script that runs the same tests that the CI is running, which I think should be achievable in a Docker container, if multiple things (i.e. Python versions) need to be set up for it. For people who will use the devcontainer proposed in #1979 in VS Code, that should be easy. For those who don't, maybe we can tell them to build the container manually and then run the tests in it. Thoughts?

### PR DESCRIPTION
**Pull request by vytas7**
Closes #1983

I was forced to add a handful of coverage `# pragma`s for CPython 3.10 due the bugs in `coveragepy` or (likely) the interpreter itself.

I added a new CI action that is triggered for `master` merges, but a successful prototype run is demonstrated here: https://github.com/falconry/falcon/runs/5260441852?check_suite_focus=true. This action simply runs `tox` with the default envlist, which has now been modernized to be fully sufficient on CPython 3.8 & 3.10 in lieu of the old `tools/mintest.sh`.

### CODE REVIEW

**Review by CaselIT — COMMENTED** [review]
It looks fine to me

**Comment by vytas7** [comment]
Still in Draft as I'm trying to figure out what to do wrt https://github.com/nedbat/coveragepy/issues/1324. There are quite many missed branches, and I don't want to plop that many `pragma`s on those lines yet...

**Comment by vytas7** [comment]
Hm, maybe I should add a newsfragment for this and call it an improvement?

**Comment by vytas7** [comment]
@CaselIT it would be awesome if you could check out the branch and give it a spin on Windows CPython 3.8 or 3.10 (just run `tox`).

**Comment by CaselIT** [comment]
> @CaselIT it would be awesome if you could check out the branch and give it a spin on Windows CPython 3.8 or 3.10 (just run `tox`).

trying on 3.9 (that's what in the env at the moment. will try the other

**Review by CaselIT — APPROVED** [review]
looks ok to me. still running

**Comment by vytas7** [comment]
3.9 has too many bugs so you won't get full coverage, otherwise nice to check (described in `CONTRIBUTING`).

**Comment by CaselIT** [comment]
it's fine also on 3.10, but the coverage still fails with 
```
falcon\routing\static.py                  110      1     48      1    99%   184
```

**Comment by vytas7** [comment]
:thinking: It passes in _Actions_ on 3.10.2... which micro version are you on with Conda?

**Comment by CaselIT** [comment]
on 3.10, yes, that's the only one.

I can take a look

**Comment by vytas7** [comment]
@CaselIT I have hopefully fixed that OS-specific discrepancy, could you please give it a spin again on 3.10 (or 3.8) on Windows?

**Review by CaselIT — APPROVED** [review]
the changes look fine to me, trying the tests to see if the coverage is fine

**Comment by CaselIT** [comment]
coverage is not fine at `falcon\routing\static.py                  111      0     48      0   100%`

**Review by CaselIT — APPROVED** [review]

**Review by kgriffs — APPROVED** [review]

**Pull request merged**
