### PR TITLE
fix: prevent pytest from collecting tests on testing.TestClient

### LINKED ISSUE #2147: Prevent Pytest from collecting tests from falcon.testing.TestClient
Let us consider we have a test case like the following:
```py
import pytest
from falcon import App, HTTP_200
from falcon.testing import TestClient

from app import create_app

@pytest.fixture(scope="session")
def app() -> App:
    """
    Initialize the app for testing.
    
    :return: The initialized app.
    """
    return create_app()

@pytest.fixture
def client(app: App) -> TestClient:
    return TestClient(app)


def test_get_books(client: TestClient) -> None:
    books = [
        {
            "name": "Life of Pi",
            "author_name": "Yann Martel",
            "isbn_code": "",
            "created_at": "",
            "updated_at": ""                
        },
        {
            "name": "Secret Six",
            "author_name": "Enid Blyton",
            "isbn_code": "",
            "created_at": "",
            "updated_at": ""                
        }
    ]
    response = client.simulate_get("/books")
    # result = json.loads(response)
    
    assert response.json == books
    assert response.status == HTTP_200
```

Notice that we are type hinting the `test_get_books` function.
Because of this (and the fact that this test function lies in another file), pytest attempts to collect tests from TestClient (as the class name starts with "Test").

error traceback:
```
(server) PS C:\Users\iyapp\OneDrive\Desktop\web-projects\library\server> pytest tests
================================================================================================================================================ test session starts ================================================================================================================================================
platform win32 -- Python 3.10.2, pytest-7.2.2, pluggy-1.0.0
rootdir: C:\Users\iyapp\OneDrive\Desktop\web-projects\library\server
collected 1 item

tests\books\test_routes.py .                                                                                                                                                                                                                                                                                   [100%]

================================================================================================================================================= warnings summary ================================================================================================================================================== 
..\..\..\..\..\.virtualenvs\server-vNBXVCHh\lib\site-packages\falcon\testing\client.py:1898
  C:\Users\iyapp\.virtualenvs\server-vNBXVCHh\lib\site-packages\falcon\testing\client.py:1898: PytestCollectionWarning: cannot collect test class 'TestClient' because it has a __init__ constructor (from: tests/books/test_routes.py)
    class TestClient:

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

This is a known issue, and can be fixed by setting:

```py
Testclient.__test__ = False
```

This is being done already by other frameworks such as starlette:
https://github.com/encode/starlette/blob/master/starlette/testclient.py#L363

I think that the TestClient class must be updated to provide similar behavior.

### PR DESCRIPTION
**Pull request by aryaniyaps**
# Summary of Changes

prevent pytest from collecting tests on testing.TestClient

# Related Issues

fixes #2147 

# Pull Request Checklist

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [x] Applied changes to both WSGI and ASGI code paths and interfaces (where applicable).
- [x] Added **tests** for changed code.
- [x] Prefixed code comments with GitHub nick and an appropriate prefix.
- [x] Coding style is consistent with the rest of the framework.
- [x] Updated **documentation** for changed code.
    - [x] Added docstrings for any new classes, functions, or modules.
    - [x] Updated docstrings for any modifications to existing code.
    - [x] Updated both WSGI and ASGI docs (where applicable).
    - [x] Added references to new classes, functions, or modules to the relevant RST file under `docs/`.
    - [x] Updated all relevant supporting documentation files under `docs/`.
    - [x] A copyright notice is included at the top of any new modules (using your own name or the name of your organization).
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/usage/restructuredtext/directives.html?highlight=versionadded#directive-versionadded).
- [x] Changes (and possible deprecations) have [towncrier](https://towncrier.readthedocs.io/en/latest/quickstart.html#creating-news-fragments) news fragments under `docs/_newsfragments/`, with the file name format `{issue_number}.{fragment_type}.rst`. (Run `towncrier --draft` to ensure it renders correctly.)

If you have *any* questions to *any* of the points above, just **submit and ask**! This checklist is here to *help* you, not to deter you from contributing!

*PR template inspired by the attrs project.*

### CODE REVIEW

**Review by CaselIT — DISMISSED** [review]

**Review by kgriffs — DISMISSED** [review]

**Review by vytas7 — CHANGES_REQUESTED** [review]
Hey there, thanks for this PR, it looked good bar some extraneous whitespace that made the `flake8` and `blue` checks fail.

However, in your latest commit you changed virtually every line of the whole codebase, we'll need to revert this one :sweat_smile:

**Review by vytas7 — CHANGES_REQUESTED** [review]
Hi again, still the same problem. Your PR proposes to change 68706 lines, basically the whole codebase, while I expect this fix to consist of 2-3 lines plus maybe a newsfragment. You need to revert unrelated changes before we can proceed with this.

**Comment by aryaniyaps** [comment]
> Hi again, still the same problem. Your PR proposes to change 68706 lines, basically the whole codebase, while I expect this fix to consist of 2-3 lines plus maybe a newsfragment. You need to revert unrelated changes before we can proceed with this.

I'm actually unsure on how to revert it. Maybe a new PR? or are there any commands to execute locally?

**Comment by CaselIT** [comment]
> > Hi again, still the same problem. Your PR proposes to change 68706 lines, basically the whole codebase, while I expect this fix to consist of 2-3 lines plus maybe a newsfragment. You need to revert unrelated changes before we can proceed with this.
> 
> I'm actually unsure on how to revert it. Maybe a new PR? or are there any commands to execute locally?

sure, feel free to close this and reopen a new PR. An alternative may be to force push on this branch applying your original change to main

**Comment by rite2hhh** [comment]
Looks like a classic CRLF (Windows) vs LF (Unix) issue

**Comment by rite2hhh** [comment]
> > Hi again, still the same problem. Your PR proposes to change 68706 lines, basically the whole codebase, while I expect this fix to consist of 2-3 lines plus maybe a newsfragment. You need to revert unrelated changes before we can proceed with this.
> 
> I'm actually unsure on how to revert it. Maybe a new PR? or are there any commands to execute locally?


Looks like a classic CRLF (Windows) vs LF (Unix) issue

If you're using vscode look at the bottom right.

image

In this image it says `LF`, if you used a Windows system to make changes, yours probably says `CRLF`.
Change it back to `LF`. If not, find a different way to revert that and you should be good to go.

Most repos use Unix convention of `LF` as the end-of-line character.

See: https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf

**Review by vytas7 — APPROVED** [review]
Thanks for bringing this up @aryaniyaps! :+1: 
I took the liberty of cleaning whitespace, as well as adding a newsfragment.

**Comment by vytas7** [comment]
And thanks for some good tips @rite2hhh!
I have now added `.editorconfig` support to the `master` branch, so if one's editor of choice (or its plugins) supports this standard, the editor should pick up Unix line endings correctly.

**Review by vytas7 — APPROVED** [review]

**Pull request merged**
