### PR TITLE
doc(contrib-snip): Clarified mailing list subscription information

### PR DESCRIPTION
**Pull request by fxfitz**
This PR simply clarifies what happens when you send your first e-mail to the mailing list.

(oh, and I also snuck a typo fix in there)

### CODE REVIEW

**Comment by kgriffs** [comment]
Thanks, this looks great! Would you also mind updating the relevant section in the README?

**Comment by fxfitz** [comment]
Will do. 

Is there any reason you wouldn't just want the README to `.. include::` the other contributing restructured text?

**Comment by kgriffs** [comment]
TBH, I don't know how well GH would handle that when rendering the markup. An alternative would be to just link to the relevant page on RTD. I suppose the same could be said for the Contributing section, although that may be better modified in a separate PR, since I think there needs to be some additional work to reconcile CONTRIBUTING.md and the RTD page regarding the same topic.

**Comment by fxfitz** [comment]
Relevant portion of the README has been updated! :-)

**Comment by kgriffs** [comment]
Looks good, thanks!

**Pull request merged**
