### PR TITLE
feat(routing): Add UUIDConverter

### PR DESCRIPTION
**Pull request by kgriffs**

### CODE REVIEW

**Comment by kgriffs** [comment]
@ueg1990 Not a bad idea. If nothing else, it will provide a self-documenting template for writing custom converters.

**Comment by ueg1990** [comment]
It shouldn't really affect performance right?

**Comment by ueg1990** [comment]
Since this issue is merged, can I open another issue and send a pull request?

**Comment by kgriffs** [comment]
@ueg1990 I don't think you need to create a new issue in this case.

**Comment by ueg1990** [comment]
ok, I will send a pull request :smile:  (i get to keep my streak going of atleast one contritbution to Falcon per year :stuck_out_tongue: )

**Pull request merged**
