### PR TITLE
Updated quickstart examples to inherit from object (new-style classes)

### PR DESCRIPTION
**Pull request by adamyala**
I went through the docs page by page and looked for where a class declaration was missing the new object inheritance.

### CODE REVIEW

**Comment by adamyala** [comment]
This pull request is in response to
https://github.com/falconry/falcon/issues/565

I wasn't sure if there was a way to link issues to pull requests

**Comment by kgriffs** [comment]
@adamyala This change looks good. Could you ammend your commit message slightly in preparation for merging? It should conform to our [style guide][2], and you can [reference the issue][1] in the body, i.e.:

```
doc(quickstart): Update examples to use new-style classes

Closes #565
```

[1]: https://github.com/blog/1386-closing-issues-via-commit-messages
[2]: https://github.com/falconry/falcon/blob/master/CONTRIBUTING.md#commit-message-format

**Comment by adamyala** [comment]
@kgriffs I rebased my commits to use the style guide (and also just used the example you gave me)

The last thing I'm not 100% clear on is the Travis CI build check. Anything specific I should do about it? Is there a type of pull request when I'd want to address it?

Sorry for all the questions, I'm new to open source contributing. I'm also working on another open issue and I'd like to save us the trouble later.

**Comment by kgriffs** [comment]
> The last thing I'm not 100% clear on is the Travis CI build check. Anything specific I should do about it? Is there a type of pull request when I'd want to address it?

For this particular change, there isn't anything to do. But if you were to modify the framework code then you would have to ensure that the tests pass, and if there aren't any tests that cover the change already, add some new ones until all code paths are tested. You can run the tests locally per the instruction on the [README][1]. It's a good idea to at least run pep8, py27, and py34 before submitting the PR:

```shell
$ tox -e pep8,py27,py34
```

If everything passes, you can submit the PR and Travis will test the remainder of the environments for you. Let me know if that helps, and feel free to catch me anytime on Freenode in #falconframework if you have further questions; I'm always happy to help new open-source contributors. :+1: 

[1]: https://github.com/falconry/falcon#test

**Comment by kgriffs** [comment]
Thanks!

**Pull request merged**
