### PR TITLE
feat: add sameSite parameter to unset_cookie

### LINKED ISSUE #2124: Request: Add sameSite parameter to unset_cookie
It would be appreciated if I could use the _unset_cookie_ method to unset a cookie I created with the parameter _sameSite='None'_. Otherwise, I'm forced to use _set_cookie_ for the sole purpose of unsetting that cookie...

With current behaviour, _sameSite_ is set to 'Lax' by default and so the browser ignores it because I'm using different domains for front and backend, and so using Cross Site requests. 

Thank you

### PR DESCRIPTION
**Pull request by TigreModerata**
# Summary of Changes

Added samesite parameter to unset_cookies, defaulting to 'Lax'.
Tests: added a test case to test_unset_cookies and to on_get in CookieUnset
Docs: added explanation of new parameter to cookies.rst

# Related Issues

Fixes #2124

# Pull Request Checklist

This is just a reminder about the most common mistakes.  Please make sure that you tick all *appropriate* boxes.  But please read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!

If an item doesn't apply to your pull request, **check it anyway** to make it apparent that there's nothing to do.

- [x] Applied changes to both WSGI and ASGI code paths and interfaces (where applicable).
- [x] Added **tests** for changed code.
- [x] Prefixed code comments with GitHub nick and an appropriate prefix.
- [x] Coding style is consistent with the rest of the framework.
- [x] Updated **documentation** for changed code.
    - [x] Added docstrings for any new classes, functions, or modules.
    - [x] Updated docstrings for any modifications to existing code.
    - [x] Updated both WSGI and ASGI docs (where applicable).
    - [x] Added references to new classes, functions, or modules to the relevant RST file under `docs/`.
    - [x] Updated all relevant supporting documentation files under `docs/`.
    - [x] A copyright notice is included at the top of any new modules (using your own name or the name of your organization).
    - [x] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/usage/restructuredtext/directives.html?highlight=versionadded#directive-versionadded).
- [x] Changes (and possible deprecations) have [towncrier](https://towncrier.readthedocs.io/en/latest/quickstart.html#creating-news-fragments) news fragments under `docs/_newsfragments/`, with the file name format `{issue_number}.{fragment_type}.rst`. (Run `towncrier --draft` to ensure it renders correctly.)

If you have *any* questions to *any* of the points above, just **submit and ask**! This checklist is here to *help* you, not to deter you from contributing!

*PR template inspired by the attrs project.*

### CODE REVIEW

**Review by vytas7 — CHANGES_REQUESTED** [review]
That looks like a great start, thanks! :100:

In order to merge this, we also need a towncrier news fragment describing the new feature; the file ought to be named `docs/_newsfragments/2124.newandimproved.rst`.

I would also like to see a couple more combinations of `samesite` covered in the unit tests in conjunction with `set_/unset_cookie(...)`.

Furthermore, it seems that some CI gates are failing, such as `pep8` & `blue`. Tip: you can simply install `blue` (`pip install -U blue`) into your environment and reformat the code (`blue .`).

**Comment by TigreModerata** [comment]
Excellent, thanks for the comments, I'll push an update asap!

**Review by vytas7 — CHANGES_REQUESTED** [review]
You need to revert `docs/changes/4.0.0.rst` -- we don't want to render that file yet, we'll probably do that at some time around the first beta release.

**Comment by TigreModerata** [comment]
> You need to revert `docs/changes/4.0.0.rst` -- we don't want to render that file yet, we'll probably do that at some time around the first beta release.

Done

**Review by CaselIT — APPROVED** [review]
thanks for the contribution

**Review by vytas7 — APPROVED** [review]
Thanks! :+1:
(I'll tweak the newsfragment later a bit because we have some others that require more cleanup anyway.)

**Review by CaselIT — APPROVED** [review]

**Comment by CaselIT** [comment]
> Thanks! 👍 (I'll tweak the newsfragment later a bit because we have some others that require more cleanup anyway.)

should also add @TigreModerata to the contridutors

**Comment by vytas7** [comment]
Yes, we run that script from time to time now, particularly before releases :slightly_smiling_face:

**Comment by TigreModerata** [comment]
Thanks to all - I will try to contribute more in the future, when I know how :)

**Comment by vytas7** [comment]
Thank you for contributing @TigreModerata!
If you want to take one more issue, let us know :slightly_smiling_face: https://github.com/falconry/falcon/issues/1010 might be a good one for new contributors, but you can of course pick whatever you like.

**Pull request merged**
