### PR TITLE
Object-based traversal

### PR DESCRIPTION
**Pull request by warsaw**
Here's a branch containing the object-based traversal subclass I'm using in my falcon branch of Mailman 3.  While probably not a full fidelity port of the restish API, it's close enough that my entire test suite passes.

For the most part, I'm PR'ing this to start a conversation about how and whether object-based traversal can be made a first class citizen of falcon.

Note that there are a number of other little helpers and utilities I'm using on top of falcon, but they're independent of the basic object-based traversal support, so I'll leave those off this branch and discuss them separately.

The tests should also give you a taste of what it looks like in practice.

### CODE REVIEW

**Comment by kgriffs** [comment]
Thanks to @richardolsson, we'll have support for pluggable routers in 0.3. Once that lands, we can bring in the object-based router engine and let users choose their own adventure.

**Comment by warsaw** [comment]
That'll be super cool.  Once this lands in trunk I'll port the Mailman 3 code over to the new scheme and see if there are any problems.

**Comment by kgriffs** [comment]
@warsaw I'm trying to decide if this is something we want to maintain in falcon directly or if it would be better maintained as a standalone package and folks could just pip install to get it. Thoughts?

**Comment by kgriffs** [comment]
Closing this PR; I think it would make sense, instead, to maintain this router as a separate add-on package as part of the broader Falcon ecosystem.

**Pull request closed without merging**
