### PR TITLE
chore(bench.bench): allow benchmarking apps implemented as generators

### PR DESCRIPTION
**Pull request by golightlyb**
Change create_bench to support WSGI applications implemented as Python generators (i.e. that yield strings or bytes).

Breaking Changes: does not affect existing benchmarks.

### CODE REVIEW

**Comment by golightlyb** [comment]
Apologies that I only intended to submit the first commit to the pull request, and keep the second only on my forked copy.

**Comment by kgriffs** [comment]
@golightlyb no worries. If you'd like to include waf2 after all, the only thing that's missing is to add the package to tools/bench-requires. FYI I'll probably split out the benchmarking module into a standalone project at some point (e.g., falconry/falcon-bench).

**Comment by golightlyb** [comment]
Hi kgriffs, I probably wouldn't include it today as waf2 isn't yet a released package and requires python >= 3.4 regardless, but thanks!

How would you like to proceed on the first commit, shall I revise the pull request or do you want to leave this pending as a feature request if falcon-bench splits off?

**Comment by kgriffs** [comment]
OK, I'd say just revise the PR to remove the waf2 commit.

**Comment by golightlyb** [comment]
Fab, hopefully I did it right! :)

**Comment by kgriffs** [comment]
Looks good!

[rebased and merged as https://github.com/falconry/falcon/pull/876]

**Pull request closed without merging**
