### PR TITLE
doc: update sponsors

### PR DESCRIPTION
**Pull request by kgriffs**

### CODE REVIEW

**Comment by kgriffs** [comment]
Partially implements #1838

**Comment by vytas7** [comment]
@KMouratidis has recently been supporting us for some months on OpenCollective, before going anonymous.
Wondering if it is OK to list him...

@KMouratidis let us know if you want your name on this list!

**Review by vytas7 — APPROVED** [review]
Looking good :+1: 

I pinged Konstantinos on Gitter, but we don't need to block on that. We can add him in a follow-up PR if we obtain a permission.

**Review by vytas7 — CHANGES_REQUESTED** [review]
Konstantinos Mouratidis (@KMouratidis) gave a permission (via Gitter) to include him, so let's do it :moneybag:

**Review by CaselIT — DISMISSED** [review]
looks good to me

**Comment by kgriffs** [comment]
Updated

**Review by vytas7 — APPROVED** [review]
:+1:

**Review by CaselIT — APPROVED** [review]

**Pull request merged**
