### PR TITLE
fix(typing): TestClient methods return Result, not _ResultBase

### PR DESCRIPTION
**Pull request by CaselIT**
Follow up of https://github.com/falconry/falcon/pull/2209 cc @davetapley

Fixes https://github.com/falconry/falcon/issues/2207

### CODE REVIEW

**Comment by CaselIT** [comment]
Moved to draft for now, I'll look at the failure next week.

@vytas7 I don't remember if we settled on installing `typing_extensions` on v4 to better support typing

**Comment by vytas7** [comment]
No, I'd love to keep the "production" installation of Falcon free of any dependencies. Is it possible to instruct the type checker to install these extensions?

Also, it is probably OK to add these dependencies on older Python versions. We don't even ship Linux wheels for some of them.

**Comment by CaselIT** [comment]
> Is it possible to instruct the type checker to install these extensions?

I don't think so.

I'll try doing something more sophisticated wrt import

**Comment by vytas7** [comment]
@CaselIT has this PR been superseded by others in the typing work stream, or should we still consider this one separately?

**Comment by CaselIT** [comment]
No, it's still relevant. I plan on finishing it once the other ones are merged

**Comment by CaselIT** [comment]
replaced by #2338

**Pull request closed without merging**
