### PR TITLE
fix(Response): Default OPTIONS responder sets Content-Length to 0

### LINKED ISSUE #796: Default OPTIONS responder does not set Content-Length to "0"
Per RFC 7231:

> A server MUST generate a Content-Length field with a value of "0" if no payload body is to be sent in the response.

### PR DESCRIPTION
**Pull request by yashmehrotra**
Closes #796

### CODE REVIEW

**Comment by painterjd** [comment]
This looks good. 

It would be nice to see a test for this, however.

**Comment by yashmehrotra** [comment]
@painterjd Hi, I have added the test for this. Please Review.
Thanks.

**Comment by kgriffs** [comment]
LGTM

**Comment by jmvrbanac** [comment]
:+1:

**Pull request merged**
