### PR TITLE
Update README to remove note about 2.0

### PR DESCRIPTION
**Pull request by lwcolton**
Now that 2.0 is released we don't need this note.

### CODE REVIEW

**Comment by kgriffs** [comment]
Nice catch. Could you also update README.rst ?

**Comment by kgriffs** [comment]
I'll take care of the RST version.

**Comment by lwcolton** [comment]
Thanks Kurt. Sorry for letting this go. Looks like we will be building our
next in house app using falcon and we appreciate your hard work so I will
try to support you as much as possible

**Comment by kgriffs** [comment]
No worries, thanks for your help!

**Pull request merged**
