### PR TITLE
Use super() where possible

### PR DESCRIPTION
**Pull request by ginoledesma**
Fixes Issue #386

### CODE REVIEW

**Comment by jmvrbanac** [comment]
:+1:

**Comment by jmvrbanac** [comment]
Could you change your commit message to conform with the documentated standard: https://github.com/falconry/falcon/blob/master/CONTRIBUTING.md#commit-message-format

**Comment by ginoledesma** [comment]
Git commit amended.

**Comment by kgriffs** [comment]
Nice work, thanks!

LGTM

**Pull request merged**
