### PR TITLE
chore: Drop support for Python 3.4

### PR DESCRIPTION
**Pull request by safaozturk93**

### CODE REVIEW

**Comment by vytas7** [comment]
Setting ``blocked-by-release`` for now, since this is slated for 3.0, not 2.0.

Another thing, probably outside the scope of this issue, but we need to consider [officially, including Tox & Travis] adding support for CPython 3.7 before/at the time of dropping support for 3.4.

**Comment by safaozturk93** [comment]
It wouldn't be a problem for me. I agree with you that Python3.7 support should be added. 👍

**Comment by kgriffs** [comment]
Agreed; we will hold this for a little bit until we open development on 3.0 later this month. I have also been thinking we need official 3.7 support for 2.0, and would love to get some help on that (README, docs, tox, travis).

**Comment by kgriffs** [comment]
Created  https://github.com/falconry/falcon/issues/1405

**Comment by vytas7** [comment]
I went on to address my comment; also removed the Python2-specific leftovers.

**Pull request merged**
