### PR TITLE
feat(status_codes) Add friendly status code names

### LINKED ISSUE #308: Friendly status code names
Add friendly names for common status codes ala https://docs.python.org/3.0/library/http.client.html

### PR DESCRIPTION
**Pull request by mcmasterathl**
Added friendly names for status codes based on https://docs.python.org/3.0/library/http.client.html.

Closes #308

### CODE REVIEW

**Comment by kgriffs** [comment]
Thanks, this looks great! Before we merge this, could you squash all the changes down to a single commit? You can do a `push --force` to reuse the same PR if you like.

**Comment by jmvrbanac** [comment]
Minus the need to squash, LGTM.

**Comment by mcmasterathl** [comment]
Squashed. Thanks guys.

**Comment by kgriffs** [comment]
LGTM

**Pull request merged**
